# Generated by Django 3.2.23 on 2024-01-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='order_items',
            new_name='items',
        ),
    ]
