# Generated by Django 3.2.23 on 2024-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20240117_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='post_code',
            field=models.CharField(blank=True, default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
