# Generated by Django 3.2.23 on 2024-01-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_ordermodel_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
